# coding: utf-8

"""
    SMS

    You can use the SMS endpoints to send and manage SMS, check the cost of sending SMS, view message history, and more. Integrate them into your system as part of your workflow.  Relevant guides: <a href=\"https://help.clicksend.com/article/h474eseq3a-how-many-characters-can-i-send-in-an-sms\" target=\"_blank\">How many characters can I send in an SMS?</a>, <a href=\"https://help.clicksend.com/article/1hd33n2xns-sms-status-delivery-receipt-expired\" target=\"_blank\">SMS status delivery receipt expired</a>, <a href=\"https://help.clicksend.com/en/articles/42195-unicode-vs-plain-text\" target=\"_blank\">Do you support non-English characters</a>, and <a href=\"https://help.clicksend.com/category/mfdctha7f0-country-specific-features-and-restrictions\" target=\"_blank\">Country Specific Features and Restrictions</a>. <div class=\"info-box\">   <h4><i class=\"fas fa-info-circle\"></i> Note :</h4>   ClickSend is pausing SMS messages containing URLs for new customers. Please remove links from messages to maintain uninterrupted delivery, or <a href=\"https://www.clicksend.com/gb/help/\" target=\"_blank\">contact support</a> to apply for approval for URL messaging. </div>

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from clicksend.models.recipient import Recipient

class TestRecipient(unittest.TestCase):
    """Recipient unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Recipient:
        """Test Recipient
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Recipient`
        """
        model = Recipient()
        if include_optional:
            return Recipient(
                user_id = 1,
                subaccount_id = 1,
                message_id = 'A00A1066-BBAE-432B-9B2D-E88969B12C46',
                address_name = 'John Smith',
                address_line_1 = 'Address 1',
                address_line_2 = '',
                address_city = 'CITY',
                address_state = 'State',
                address_postal_code = '123456',
                address_country = 'AU',
                return_address_id = 1,
                custom_string = 'kn0ChLhwn6',
                schedule = 1449573604,
                source = '.rest.v3',
                colour = 1,
                duplex = 0,
                post_pages = 7,
                post_price = '13.4200',
                priority_post = 0,
                date_added = 1459131623,
                status = 'SUCCESS',
                file_url = 'http://yourdomain.com/file.pdf',
                return_address = clicksend.models.postcard_recipient__return_address.postcard_recipient__return_address(
                    return_address_id = 56, 
                    user_id = 56, 
                    address_name = '', 
                    address_line_1 = '', 
                    address_line_2 = '', 
                    address_city = '', 
                    address_state = '', 
                    address_postal_code = '', 
                    address_country = '', ),
                api_username = 'my_api_username'
            )
        else:
            return Recipient(
        )
        """

    def testRecipient(self):
        """Test Recipient"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
