# coding: utf-8

"""
    SMS

    You can use the SMS endpoints to send and manage SMS, check the cost of sending SMS, view message history, and more. Integrate them into your system as part of your workflow.  Relevant guides: <a href=\"https://help.clicksend.com/article/h474eseq3a-how-many-characters-can-i-send-in-an-sms\" target=\"_blank\">How many characters can I send in an SMS?</a>, <a href=\"https://help.clicksend.com/article/1hd33n2xns-sms-status-delivery-receipt-expired\" target=\"_blank\">SMS status delivery receipt expired</a>, <a href=\"https://help.clicksend.com/en/articles/42195-unicode-vs-plain-text\" target=\"_blank\">Do you support non-English characters</a>, and <a href=\"https://help.clicksend.com/category/mfdctha7f0-country-specific-features-and-restrictions\" target=\"_blank\">Country Specific Features and Restrictions</a>. <div class=\"info-box\">   <h4><i class=\"fas fa-info-circle\"></i> Note :</h4>   ClickSend is pausing SMS messages containing URLs for new customers. Please remove links from messages to maintain uninterrupted delivery, or <a href=\"https://www.clicksend.com/gb/help/\" target=\"_blank\">contact support</a> to apply for approval for URL messaging. </div>

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from clicksend.models.get_default_sender_details import GetDefaultSenderDetails

class TestGetDefaultSenderDetails(unittest.TestCase):
    """GetDefaultSenderDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetDefaultSenderDetails:
        """Test GetDefaultSenderDetails
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetDefaultSenderDetails`
        """
        model = GetDefaultSenderDetails()
        if include_optional:
            return GetDefaultSenderDetails(
                http_code = 200,
                response_code = 'SUCCESS',
                response_msg = 'Operation completed successfully',
                data = clicksend.models.default_sender.default_sender(
                    id = 'f99872cc-11a6-48ba-a9f2-bcfb6dd1e3d4', 
                    user_id = 123456, 
                    subaccount_id = 45678, 
                    country_code = 'AU', 
                    product_type = 'SMS', 
                    default_sender_strategies = [
                        clicksend.models.default_sender_default_sender_strategies_inner.default_sender_default_sender_strategies_inner(
                            sender_type = 'alpha_tag', 
                            sender_id = 'ClickSend', 
                            sender_country_code = '', 
                            priority = 1, 
                            status = 'ENABLED', 
                            note = 'This is a test default sender', )
                        ], 
                    status = 'ENABLED', 
                    created_timestamp = '2021-08-02T00:00:00Z', 
                    updated_timestamp = '2021-08-02T00:00:00Z', )
            )
        else:
            return GetDefaultSenderDetails(
                http_code = 200,
                response_code = 'SUCCESS',
                response_msg = 'Operation completed successfully',
                data = clicksend.models.default_sender.default_sender(
                    id = 'f99872cc-11a6-48ba-a9f2-bcfb6dd1e3d4', 
                    user_id = 123456, 
                    subaccount_id = 45678, 
                    country_code = 'AU', 
                    product_type = 'SMS', 
                    default_sender_strategies = [
                        clicksend.models.default_sender_default_sender_strategies_inner.default_sender_default_sender_strategies_inner(
                            sender_type = 'alpha_tag', 
                            sender_id = 'ClickSend', 
                            sender_country_code = '', 
                            priority = 1, 
                            status = 'ENABLED', 
                            note = 'This is a test default sender', )
                        ], 
                    status = 'ENABLED', 
                    created_timestamp = '2021-08-02T00:00:00Z', 
                    updated_timestamp = '2021-08-02T00:00:00Z', ),
        )
        """

    def testGetDefaultSenderDetails(self):
        """Test GetDefaultSenderDetails"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
