# coding: utf-8

"""
    SMS

    You can use the SMS endpoints to send and manage SMS, check the cost of sending SMS, view message history, and more. Integrate them into your system as part of your workflow.  Relevant guides: <a href=\"https://help.clicksend.com/article/h474eseq3a-how-many-characters-can-i-send-in-an-sms\" target=\"_blank\">How many characters can I send in an SMS?</a>, <a href=\"https://help.clicksend.com/article/1hd33n2xns-sms-status-delivery-receipt-expired\" target=\"_blank\">SMS status delivery receipt expired</a>, <a href=\"https://help.clicksend.com/en/articles/42195-unicode-vs-plain-text\" target=\"_blank\">Do you support non-English characters</a>, and <a href=\"https://help.clicksend.com/category/mfdctha7f0-country-specific-features-and-restrictions\" target=\"_blank\">Country Specific Features and Restrictions</a>. <div class=\"info-box\">   <h4><i class=\"fas fa-info-circle\"></i> Note :</h4>   ClickSend is pausing SMS messages containing URLs for new customers. Please remove links from messages to maintain uninterrupted delivery, or <a href=\"https://www.clicksend.com/gb/help/\" target=\"_blank\">contact support</a> to apply for approval for URL messaging. </div>

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from clicksend.models.view_fax_delivery_receipt_rules_data import ViewFaxDeliveryReceiptRulesData

class TestViewFaxDeliveryReceiptRulesData(unittest.TestCase):
    """ViewFaxDeliveryReceiptRulesData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ViewFaxDeliveryReceiptRulesData:
        """Test ViewFaxDeliveryReceiptRulesData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ViewFaxDeliveryReceiptRulesData`
        """
        model = ViewFaxDeliveryReceiptRulesData()
        if include_optional:
            return ViewFaxDeliveryReceiptRulesData(
                total = 2,
                per_page = 15,
                current_page = 1,
                last_page = 1,
                next_page_url = '',
                prev_page_url = '',
                var_from = 1,
                to = 2,
                data = [{"receipt_rule_id":1,"rule_name":"Email Test Rule","match_type":0,"action":"URL","action_address":"http://yourdomain.com","enabled":1},{"receipt_rule_id":2,"rule_name":"test","match_type":0,"action":"URL","action_address":"http://yourdomain.com","enabled":1}]
            )
        else:
            return ViewFaxDeliveryReceiptRulesData(
        )
        """

    def testViewFaxDeliveryReceiptRulesData(self):
        """Test ViewFaxDeliveryReceiptRulesData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
