# coding: utf-8

"""
    SMS

    You can use the SMS endpoints to send and manage SMS, check the cost of sending SMS, view message history, and more. Integrate them into your system as part of your workflow.  Relevant guides: <a href=\"https://help.clicksend.com/article/h474eseq3a-how-many-characters-can-i-send-in-an-sms\" target=\"_blank\">How many characters can I send in an SMS?</a>, <a href=\"https://help.clicksend.com/article/1hd33n2xns-sms-status-delivery-receipt-expired\" target=\"_blank\">SMS status delivery receipt expired</a>, <a href=\"https://help.clicksend.com/en/articles/42195-unicode-vs-plain-text\" target=\"_blank\">Do you support non-English characters</a>, and <a href=\"https://help.clicksend.com/category/mfdctha7f0-country-specific-features-and-restrictions\" target=\"_blank\">Country Specific Features and Restrictions</a>. <div class=\"info-box\">   <h4><i class=\"fas fa-info-circle\"></i> Note :</h4>   ClickSend is pausing SMS messages containing URLs for new customers. Please remove links from messages to maintain uninterrupted delivery, or <a href=\"https://www.clicksend.com/gb/help/\" target=\"_blank\">contact support</a> to apply for approval for URL messaging. </div>

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from clicksend.models.view_referral_accounts_data_all_of_data_inner import ViewReferralAccountsDataAllOfDataInner

class TestViewReferralAccountsDataAllOfDataInner(unittest.TestCase):
    """ViewReferralAccountsDataAllOfDataInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ViewReferralAccountsDataAllOfDataInner:
        """Test ViewReferralAccountsDataAllOfDataInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ViewReferralAccountsDataAllOfDataInner`
        """
        model = ViewReferralAccountsDataAllOfDataInner()
        if include_optional:
            return ViewReferralAccountsDataAllOfDataInner(
                referral_rule_id = 56,
                refered_user_id = 56,
                date_referred = 1438260940,
                percentage_referral = 5
            )
        else:
            return ViewReferralAccountsDataAllOfDataInner(
        )
        """

    def testViewReferralAccountsDataAllOfDataInner(self):
        """Test ViewReferralAccountsDataAllOfDataInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
