# coding: utf-8

"""
    SMS

    You can use the SMS endpoints to send and manage SMS, check the cost of sending SMS, view message history, and more. Integrate them into your system as part of your workflow.  Relevant guides: <a href=\"https://help.clicksend.com/article/h474eseq3a-how-many-characters-can-i-send-in-an-sms\" target=\"_blank\">How many characters can I send in an SMS?</a>, <a href=\"https://help.clicksend.com/article/1hd33n2xns-sms-status-delivery-receipt-expired\" target=\"_blank\">SMS status delivery receipt expired</a>, <a href=\"https://help.clicksend.com/en/articles/42195-unicode-vs-plain-text\" target=\"_blank\">Do you support non-English characters</a>, and <a href=\"https://help.clicksend.com/category/mfdctha7f0-country-specific-features-and-restrictions\" target=\"_blank\">Country Specific Features and Restrictions</a>. <div class=\"info-box\">   <h4><i class=\"fas fa-info-circle\"></i> Note :</h4>   ClickSend is pausing SMS messages containing URLs for new customers. Please remove links from messages to maintain uninterrupted delivery, or <a href=\"https://www.clicksend.com/gb/help/\" target=\"_blank\">contact support</a> to apply for approval for URL messaging. </div>

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from clicksend.api.sms_other_api import SmsOtherApi


class TestSmsOtherApi(unittest.TestCase):
    """SmsOtherApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SmsOtherApi()

    def tearDown(self) -> None:
        pass

    def test_calculate_sms_price(self) -> None:
        """Test case for calculate_sms_price

        Calculate SMS Price
        """
        pass

    def test_cancel_all_sms(self) -> None:
        """Test case for cancel_all_sms

        Cancel All SMS
        """
        pass

    def test_cancel_sms(self) -> None:
        """Test case for cancel_sms

        Cancel SMS
        """
        pass

    def test_create_sms_delivery_receipt_rule(self) -> None:
        """Test case for create_sms_delivery_receipt_rule

        Create SMS Delivery Receipt Rule
        """
        pass

    def test_create_sms_inbound_automation(self) -> None:
        """Test case for create_sms_inbound_automation

        Create SMS Inbound Automation
        """
        pass

    def test_create_sms_template(self) -> None:
        """Test case for create_sms_template

        Create SMS Template
        """
        pass

    def test_create_test_inbound_sms(self) -> None:
        """Test case for create_test_inbound_sms

        Create Test Inbound SMS
        """
        pass

    def test_create_test_sms_receipt(self) -> None:
        """Test case for create_test_sms_receipt

        Create Test SMS Receipt
        """
        pass

    def test_delete_sms_delivery_receipt_rule(self) -> None:
        """Test case for delete_sms_delivery_receipt_rule

        Delete SMS Delivery Receipt Rule
        """
        pass

    def test_delete_sms_inbound_automation(self) -> None:
        """Test case for delete_sms_inbound_automation

        Delete SMS Inbound Automation
        """
        pass

    def test_delete_sms_template(self) -> None:
        """Test case for delete_sms_template

        Delete SMS Template
        """
        pass

    def test_export_sms_history(self) -> None:
        """Test case for export_sms_history

        Export SMS History
        """
        pass

    def test_mark_inbound_sms_as_read(self) -> None:
        """Test case for mark_inbound_sms_as_read

        Mark Inbound SMS as Read
        """
        pass

    def test_mark_sms_receipt_as_read(self) -> None:
        """Test case for mark_sms_receipt_as_read

        Mark SMS Receipt As Read
        """
        pass

    def test_mark_specific_inbound_sms_message_as_read(self) -> None:
        """Test case for mark_specific_inbound_sms_message_as_read

        Mark Specific Inbound SMS Message As Read
        """
        pass

    def test_send_sms(self) -> None:
        """Test case for send_sms

        Send SMS
        """
        pass

    def test_update_sms_delivery_receipt_rule(self) -> None:
        """Test case for update_sms_delivery_receipt_rule

        Update SMS Delivery Receipt Rule
        """
        pass

    def test_update_sms_inbound_automation(self) -> None:
        """Test case for update_sms_inbound_automation

        Update SMS Inbound Automation
        """
        pass

    def test_update_sms_template(self) -> None:
        """Test case for update_sms_template

        Update SMS Template
        """
        pass

    def test_view_a_specific_inbound_sms_message(self) -> None:
        """Test case for view_a_specific_inbound_sms_message

        View a specific inbound SMS message
        """
        pass

    def test_view_a_specific_sms_template(self) -> None:
        """Test case for view_a_specific_sms_template

        View a Specific SMS Template
        """
        pass

    def test_view_inbound_sms(self) -> None:
        """Test case for view_inbound_sms

        View Inbound SMS
        """
        pass

    def test_view_sms_delivery_receipt_rule(self) -> None:
        """Test case for view_sms_delivery_receipt_rule

        View SMS Delivery Receipt Rule
        """
        pass

    def test_view_sms_delivery_receipt_rules(self) -> None:
        """Test case for view_sms_delivery_receipt_rules

        View SMS Delivery Receipt Rules
        """
        pass

    def test_view_sms_history(self) -> None:
        """Test case for view_sms_history

        View SMS History
        """
        pass

    def test_view_sms_inbound_automation(self) -> None:
        """Test case for view_sms_inbound_automation

        View SMS Inbound Automation
        """
        pass

    def test_view_sms_inbound_automations(self) -> None:
        """Test case for view_sms_inbound_automations

        View SMS Inbound Automations
        """
        pass

    def test_view_sms_receipts(self) -> None:
        """Test case for view_sms_receipts

        View SMS Receipts
        """
        pass

    def test_view_sms_templates(self) -> None:
        """Test case for view_sms_templates

        View SMS Templates
        """
        pass

    def test_view_specific_sms_receipt(self) -> None:
        """Test case for view_specific_sms_receipt

        View Specific SMS Receipt
        """
        pass


if __name__ == '__main__':
    unittest.main()
