# coding: utf-8

"""
    SMS

    You can use the SMS endpoints to send and manage SMS, check the cost of sending SMS, view message history, and more. Integrate them into your system as part of your workflow.  Relevant guides: <a href=\"https://help.clicksend.com/article/h474eseq3a-how-many-characters-can-i-send-in-an-sms\" target=\"_blank\">How many characters can I send in an SMS?</a>, <a href=\"https://help.clicksend.com/article/1hd33n2xns-sms-status-delivery-receipt-expired\" target=\"_blank\">SMS status delivery receipt expired</a>, <a href=\"https://help.clicksend.com/en/articles/42195-unicode-vs-plain-text\" target=\"_blank\">Do you support non-English characters</a>, and <a href=\"https://help.clicksend.com/category/mfdctha7f0-country-specific-features-and-restrictions\" target=\"_blank\">Country Specific Features and Restrictions</a>. <div class=\"info-box\">   <h4><i class=\"fas fa-info-circle\"></i> Note :</h4>   ClickSend is pausing SMS messages containing URLs for new customers. Please remove links from messages to maintain uninterrupted delivery, or <a href=\"https://www.clicksend.com/gb/help/\" target=\"_blank\">contact support</a> to apply for approval for URL messaging. </div>

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from clicksend.api.reseller_other_api import ResellerOtherApi


class TestResellerOtherApi(unittest.TestCase):
    """ResellerOtherApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ResellerOtherApi()

    def tearDown(self) -> None:
        pass

    def test_create_reseller_account(self) -> None:
        """Test case for create_reseller_account

        Create Reseller Account
        """
        pass

    def test_reseller_transfer_credit(self) -> None:
        """Test case for reseller_transfer_credit

        Reseller Transfer Credit
        """
        pass

    def test_update_client_account(self) -> None:
        """Test case for update_client_account

        Update Client Account
        """
        pass

    def test_view_client_accounts(self) -> None:
        """Test case for view_client_accounts

        View Client Accounts
        """
        pass

    def test_view_specific_client_account(self) -> None:
        """Test case for view_specific_client_account

        View Specific Client Account
        """
        pass


if __name__ == '__main__':
    unittest.main()
