# coding: utf-8

"""
    SMS

    You can use the SMS endpoints to send and manage SMS, check the cost of sending SMS, view message history, and more. Integrate them into your system as part of your workflow.  Relevant guides: <a href=\"https://help.clicksend.com/article/h474eseq3a-how-many-characters-can-i-send-in-an-sms\" target=\"_blank\">How many characters can I send in an SMS?</a>, <a href=\"https://help.clicksend.com/article/1hd33n2xns-sms-status-delivery-receipt-expired\" target=\"_blank\">SMS status delivery receipt expired</a>, <a href=\"https://help.clicksend.com/en/articles/42195-unicode-vs-plain-text\" target=\"_blank\">Do you support non-English characters</a>, and <a href=\"https://help.clicksend.com/category/mfdctha7f0-country-specific-features-and-restrictions\" target=\"_blank\">Country Specific Features and Restrictions</a>. <div class=\"info-box\">   <h4><i class=\"fas fa-info-circle\"></i> Note :</h4>   ClickSend is pausing SMS messages containing URLs for new customers. Please remove links from messages to maintain uninterrupted delivery, or <a href=\"https://www.clicksend.com/gb/help/\" target=\"_blank\">contact support</a> to apply for approval for URL messaging. </div>

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class AlphaTag(BaseModel):
    """
    AlphaTag
    """ # noqa: E501
    id: Optional[StrictStr] = Field(default=None, description="The unique identifier for the record.", json_schema_extra={"examples": ["db630385-cb76-457d-8f16-76df1b394257"]})
    account_id: Optional[StrictStr] = Field(default=None, description="The unique identifier for the account.", json_schema_extra={"examples": ["85edb794-ee6d-4a38-9f63-c5fa8acf0d79"]})
    workspace_id: Optional[StrictStr] = Field(default=None, description="The unique identifier for the workspace.", json_schema_extra={"examples": ["85edb794-ee6d-4a38-9f63-c5fa8acf0d79"]})
    user_id: Optional[StrictStr] = Field(default=None, description="The unique identifier for the user.", json_schema_extra={"examples": ["85edb794-ee6d-4a38-9f63-c5fa8acf0d79"]})
    alpha_tag: Optional[StrictStr] = Field(default=None, description="The alpha tag.", json_schema_extra={"examples": ["Abc123"]})
    status: Optional[StrictStr] = Field(default=None, description="The status of the record.", json_schema_extra={"examples": ["PENDING"]})
    reason: Optional[StrictStr] = Field(default=None, description="The reason for the status.", json_schema_extra={"examples": ["Sole Trader Name"]})
    countries: Optional[List[StrictStr]] = Field(default=None, description="List of country codes where the alpha tag is requested. If not provided, it means a global alpha tag.", json_schema_extra={"examples": [["AU"]]})
    created_timestamp: Optional[datetime] = Field(default=None, description="The timestamp when the record was created.", json_schema_extra={"examples": ["2021-05-11T01:00:00.123Z"]})
    updated_timestamp: Optional[datetime] = Field(default=None, description="The timestamp when the record was last updated.", json_schema_extra={"examples": ["2021-05-11T01:05:00.123Z"]})
    __properties: ClassVar[List[str]] = ["id", "account_id", "workspace_id", "user_id", "alpha_tag", "status", "reason", "countries", "created_timestamp", "updated_timestamp"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AlphaTag from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if countries (nullable) is None
        # and model_fields_set contains the field
        if self.countries is None and "countries" in self.model_fields_set:
            _dict['countries'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AlphaTag from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "account_id": obj.get("account_id"),
            "workspace_id": obj.get("workspace_id"),
            "user_id": obj.get("user_id"),
            "alpha_tag": obj.get("alpha_tag"),
            "status": obj.get("status"),
            "reason": obj.get("reason"),
            "countries": obj.get("countries"),
            "created_timestamp": obj.get("created_timestamp"),
            "updated_timestamp": obj.get("updated_timestamp")
        })
        return _obj


