# coding: utf-8

"""
    SMS

    You can use the SMS endpoints to send and manage SMS, check the cost of sending SMS, view message history, and more. Integrate them into your system as part of your workflow.  Relevant guides: <a href=\"https://help.clicksend.com/article/h474eseq3a-how-many-characters-can-i-send-in-an-sms\" target=\"_blank\">How many characters can I send in an SMS?</a>, <a href=\"https://help.clicksend.com/article/1hd33n2xns-sms-status-delivery-receipt-expired\" target=\"_blank\">SMS status delivery receipt expired</a>, <a href=\"https://help.clicksend.com/en/articles/42195-unicode-vs-plain-text\" target=\"_blank\">Do you support non-English characters</a>, and <a href=\"https://help.clicksend.com/category/mfdctha7f0-country-specific-features-and-restrictions\" target=\"_blank\">Country Specific Features and Restrictions</a>. <div class=\"info-box\">   <h4><i class=\"fas fa-info-circle\"></i> Note :</h4>   ClickSend is pausing SMS messages containing URLs for new customers. Please remove links from messages to maintain uninterrupted delivery, or <a href=\"https://www.clicksend.com/gb/help/\" target=\"_blank\">contact support</a> to apply for approval for URL messaging. </div>

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from clicksend.models.calculate_sms_price_data_summary_countries_inner_country_regulation_created_at import CalculateSmsPriceDataSummaryCountriesInnerCountryRegulationCreatedAt
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CalculateSmsPriceDataSummaryCountriesInnerCountryRegulation(BaseModel):
    """
    The parameters related to the country guidelines on the user level.
    """ # noqa: E501
    country_user_id: Optional[StrictInt] = Field(default=None, description="Your identifier for the country regulation.")
    sms_registration_type: Optional[StrictInt] = Field(default=None, description="The global sending requirement for this country. It can be one of the following:  - **0:** No number or account registration required.      - **1:** Number registration required. You can purchase a registered number from ClickSend. Examples: US and CA.      - **2:** Account registration required. You can register your company details or business details to register your account. Examples: NZ, SG and UAE.  This parameter is a duplicate of registration_type.  <div class=\"info-box\">   <h4><i class=\"fas fa-info-circle\"></i> Note:</h4>   <p>This parameter is fixed and can't be changed based on your settings.</p> </div>")
    restricted_sending: Optional[StrictBool] = Field(default=None, description="Indicates whether you have any restriction for sending the message to this country:  - **True:** You're restricted from sending messages to this country, possibly due to not having a registered number.      - **False:** You're not restricted from sending messages to this country.")
    trial_sending: Optional[StrictBool] = Field(default=None, description="Indicates whether the country supports trial sending or not:  - **True:** This country supports trial sending      - **False:** This country doesn’t support trial sending  Countries with restricted sending typically offers trial sending. With trial sending, you can send messages to the country without registering your number or account.  <div class=\"info-box\">   <h4><i class=\"fas fa-info-circle\"></i> Note:</h4>   <p>Trial sending has limitations, such as a daily limit of 200 messages in some countries. The limitations vary by country. <br/><br/> This parameter is fixed and can't be changed based on your settings.</p> </div>")
    regulation_requirements_description: Optional[StrictStr] = Field(default=None, description="The text description of the regulatory requirements.")
    created_at: Optional[CalculateSmsPriceDataSummaryCountriesInnerCountryRegulationCreatedAt] = None
    updated_at: Optional[CalculateSmsPriceDataSummaryCountriesInnerCountryRegulationCreatedAt] = None
    __properties: ClassVar[List[str]] = ["country_user_id", "sms_registration_type", "restricted_sending", "trial_sending", "regulation_requirements_description", "created_at", "updated_at"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CalculateSmsPriceDataSummaryCountriesInnerCountryRegulation from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of created_at
        if self.created_at:
            _dict['created_at'] = self.created_at.to_dict()
        # override the default output from pydantic by calling `to_dict()` of updated_at
        if self.updated_at:
            _dict['updated_at'] = self.updated_at.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CalculateSmsPriceDataSummaryCountriesInnerCountryRegulation from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "country_user_id": obj.get("country_user_id"),
            "sms_registration_type": obj.get("sms_registration_type"),
            "restricted_sending": obj.get("restricted_sending"),
            "trial_sending": obj.get("trial_sending"),
            "regulation_requirements_description": obj.get("regulation_requirements_description"),
            "created_at": CalculateSmsPriceDataSummaryCountriesInnerCountryRegulationCreatedAt.from_dict(obj["created_at"]) if obj.get("created_at") is not None else None,
            "updated_at": CalculateSmsPriceDataSummaryCountriesInnerCountryRegulationCreatedAt.from_dict(obj["updated_at"]) if obj.get("updated_at") is not None else None
        })
        return _obj


