# coding: utf-8

"""
    SMS

    You can use the SMS endpoints to send and manage SMS, check the cost of sending SMS, view message history, and more. Integrate them into your system as part of your workflow.  Relevant guides: <a href=\"https://help.clicksend.com/article/h474eseq3a-how-many-characters-can-i-send-in-an-sms\" target=\"_blank\">How many characters can I send in an SMS?</a>, <a href=\"https://help.clicksend.com/article/1hd33n2xns-sms-status-delivery-receipt-expired\" target=\"_blank\">SMS status delivery receipt expired</a>, <a href=\"https://help.clicksend.com/en/articles/42195-unicode-vs-plain-text\" target=\"_blank\">Do you support non-English characters</a>, and <a href=\"https://help.clicksend.com/category/mfdctha7f0-country-specific-features-and-restrictions\" target=\"_blank\">Country Specific Features and Restrictions</a>. <div class=\"info-box\">   <h4><i class=\"fas fa-info-circle\"></i> Note :</h4>   ClickSend is pausing SMS messages containing URLs for new customers. Please remove links from messages to maintain uninterrupted delivery, or <a href=\"https://www.clicksend.com/gb/help/\" target=\"_blank\">contact support</a> to apply for approval for URL messaging. </div>

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class DefaultSenderDefaultSenderStrategiesInner(BaseModel):
    """
    DefaultSenderDefaultSenderStrategiesInner
    """ # noqa: E501
    sender_type: StrictStr = Field(description="Type of the sender.", json_schema_extra={"examples": ["alpha_tag"]})
    sender_id: StrictStr = Field(description="Identifier for the sender. Must be between 3-20 characters.", json_schema_extra={"examples": ["ClickSend"]})
    sender_country_code: Optional[StrictStr] = Field(default=None, description="ISO 3166-1 alpha-2 formatted country code.")
    priority: StrictInt = Field(description="Priority level of the sender in the strategy. Must be a positive integer.", json_schema_extra={"examples": [1]})
    status: StrictStr = Field(description="Status of the sender in the strategy.", json_schema_extra={"examples": ["ENABLED"]})
    note: Optional[StrictStr] = Field(default=None, description="Note providing additional context about the sender. Maximum length of 200 characters. Optional.", json_schema_extra={"examples": ["This is a test default sender"]})
    __properties: ClassVar[List[str]] = ["sender_type", "sender_id", "sender_country_code", "priority", "status", "note"]

    @field_validator('sender_type')
    def sender_type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['alpha_tag', '10DLC', 'tollfree', 'own_number', 'shortcode', 'longcode', 'shared_longcode']):
            raise ValueError("must be one of enum values ('alpha_tag', '10DLC', 'tollfree', 'own_number', 'shortcode', 'longcode', 'shared_longcode')")
        return value

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['ENABLED', 'DISABLED']):
            raise ValueError("must be one of enum values ('ENABLED', 'DISABLED')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DefaultSenderDefaultSenderStrategiesInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DefaultSenderDefaultSenderStrategiesInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "sender_type": obj.get("sender_type"),
            "sender_id": obj.get("sender_id"),
            "sender_country_code": obj.get("sender_country_code"),
            "priority": obj.get("priority"),
            "status": obj.get("status"),
            "note": obj.get("note")
        })
        return _obj


