# coding: utf-8

"""
    SMS

    You can use the SMS endpoints to send and manage SMS, check the cost of sending SMS, view message history, and more. Integrate them into your system as part of your workflow.  Relevant guides: <a href=\"https://help.clicksend.com/article/h474eseq3a-how-many-characters-can-i-send-in-an-sms\" target=\"_blank\">How many characters can I send in an SMS?</a>, <a href=\"https://help.clicksend.com/article/1hd33n2xns-sms-status-delivery-receipt-expired\" target=\"_blank\">SMS status delivery receipt expired</a>, <a href=\"https://help.clicksend.com/en/articles/42195-unicode-vs-plain-text\" target=\"_blank\">Do you support non-English characters</a>, and <a href=\"https://help.clicksend.com/category/mfdctha7f0-country-specific-features-and-restrictions\" target=\"_blank\">Country Specific Features and Restrictions</a>. <div class=\"info-box\">   <h4><i class=\"fas fa-info-circle\"></i> Note :</h4>   ClickSend is pausing SMS messages containing URLs for new customers. Please remove links from messages to maintain uninterrupted delivery, or <a href=\"https://www.clicksend.com/gb/help/\" target=\"_blank\">contact support</a> to apply for approval for URL messaging. </div>

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class Fax(BaseModel):
    """
    Fax
    """ # noqa: E501
    user_id: Optional[StrictInt] = Field(default=None, description="The ID of the user.", json_schema_extra={"examples": [1]})
    subaccount_id: Optional[StrictInt] = Field(default=None, description="The ID of the subaccount.", json_schema_extra={"examples": [1]})
    list_id: Optional[StrictInt] = Field(default=None, description="The ID of the list.")
    message_id: Optional[StrictStr] = Field(default=None, description="The ID of the message.", json_schema_extra={"examples": ["6BBEB11E-CAA6-4B04-8537-63619F3D6B37"]})
    to: Optional[StrictStr] = Field(default=None, description="The recipient's phone number.", json_schema_extra={"examples": ["+61261111122"]})
    var_from: Optional[StrictStr] = Field(default=None, description="The sender's phone number.", alias="from", json_schema_extra={"examples": ["+61298441484"]})
    carrier: Optional[StrictStr] = Field(default=None, description="The carrier associated with the message.", json_schema_extra={"examples": [""]})
    country: Optional[StrictStr] = Field(default=None, description="The country code.", json_schema_extra={"examples": ["AU"]})
    custom_string: Optional[StrictStr] = Field(default=None, description="A custom string associated with the message.", json_schema_extra={"examples": ["custom_string"]})
    schedule: Optional[StrictStr] = Field(default=None, description="The scheduled time for sending the message.", json_schema_extra={"examples": ["1436874701"]})
    message_pages: Optional[StrictInt] = Field(default=None, description="The number of pages in the message.", json_schema_extra={"examples": [6]})
    message_price: Optional[StrictStr] = Field(default=None, description="The price of the message.", json_schema_extra={"examples": ["13.2000"]})
    status_code: Optional[StrictStr] = Field(default=None, description="The status code of the message.", json_schema_extra={"examples": ["201"]})
    status_text: Optional[StrictStr] = Field(default=None, description="The status text of the message.", json_schema_extra={"examples": ["Sent"]})
    date_added: Optional[StrictInt] = Field(default=None, description="The date when the message was added.", json_schema_extra={"examples": [1457504350]})
    from_email: Optional[StrictStr] = Field(default=None, description="The sender's email address.", json_schema_extra={"examples": ["john@doe.com"]})
    file_url: Optional[StrictStr] = Field(default=None, description="The URL of the file associated with the message.", alias="_file_url", json_schema_extra={"examples": ["https://rest.clicksend.com/files/98DDA1A4-8A74-4831-8FAF-CC4B4EBD8241.pdf"]})
    status: Optional[StrictStr] = Field(default=None, description="The status of the message.", json_schema_extra={"examples": ["SUCCESS"]})
    __properties: ClassVar[List[str]] = ["user_id", "subaccount_id", "list_id", "message_id", "to", "from", "carrier", "country", "custom_string", "schedule", "message_pages", "message_price", "status_code", "status_text", "date_added", "from_email", "_file_url", "status"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Fax from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if list_id (nullable) is None
        # and model_fields_set contains the field
        if self.list_id is None and "list_id" in self.model_fields_set:
            _dict['list_id'] = None

        # set to None if status_code (nullable) is None
        # and model_fields_set contains the field
        if self.status_code is None and "status_code" in self.model_fields_set:
            _dict['status_code'] = None

        # set to None if status_text (nullable) is None
        # and model_fields_set contains the field
        if self.status_text is None and "status_text" in self.model_fields_set:
            _dict['status_text'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Fax from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "user_id": obj.get("user_id"),
            "subaccount_id": obj.get("subaccount_id"),
            "list_id": obj.get("list_id"),
            "message_id": obj.get("message_id"),
            "to": obj.get("to"),
            "from": obj.get("from"),
            "carrier": obj.get("carrier"),
            "country": obj.get("country"),
            "custom_string": obj.get("custom_string"),
            "schedule": obj.get("schedule"),
            "message_pages": obj.get("message_pages"),
            "message_price": obj.get("message_price"),
            "status_code": obj.get("status_code"),
            "status_text": obj.get("status_text"),
            "date_added": obj.get("date_added"),
            "from_email": obj.get("from_email"),
            "_file_url": obj.get("_file_url"),
            "status": obj.get("status")
        })
        return _obj


