# coding: utf-8

"""
    SMS

    You can use the SMS endpoints to send and manage SMS, check the cost of sending SMS, view message history, and more. Integrate them into your system as part of your workflow.  Relevant guides: <a href=\"https://help.clicksend.com/article/h474eseq3a-how-many-characters-can-i-send-in-an-sms\" target=\"_blank\">How many characters can I send in an SMS?</a>, <a href=\"https://help.clicksend.com/article/1hd33n2xns-sms-status-delivery-receipt-expired\" target=\"_blank\">SMS status delivery receipt expired</a>, <a href=\"https://help.clicksend.com/en/articles/42195-unicode-vs-plain-text\" target=\"_blank\">Do you support non-English characters</a>, and <a href=\"https://help.clicksend.com/category/mfdctha7f0-country-specific-features-and-restrictions\" target=\"_blank\">Country Specific Features and Restrictions</a>. <div class=\"info-box\">   <h4><i class=\"fas fa-info-circle\"></i> Note :</h4>   ClickSend is pausing SMS messages containing URLs for new customers. Please remove links from messages to maintain uninterrupted delivery, or <a href=\"https://www.clicksend.com/gb/help/\" target=\"_blank\">contact support</a> to apply for approval for URL messaging. </div>

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from clicksend.models.currency import Currency
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class PurchaseDedicatedNumberData(BaseModel):
    """
    PurchaseDedicatedNumberData
    """ # noqa: E501
    dedicated_number: Optional[StrictStr] = Field(default=None, description="The new dedicated number.", json_schema_extra={"examples": ["+12282060576"]})
    country: Optional[StrictStr] = Field(default=None, description="The country code of the new dedicated number.", json_schema_extra={"examples": ["US"]})
    price_total: Optional[StrictStr] = Field(default=None, description="The total price of the new dedicated number.", json_schema_extra={"examples": ["8.98"]})
    price_setup: Optional[StrictStr] = Field(default=None, description="The setup price of the new dedicated number.", alias="_price_setup", json_schema_extra={"examples": ["22.22"]})
    price_monthly: Optional[StrictStr] = Field(default=None, description="The monthly price of the new dedicated number.", alias="_price_monthly", json_schema_extra={"examples": ["11.11"]})
    currency: Optional[Currency] = Field(default=None, alias="_currency")
    __properties: ClassVar[List[str]] = ["dedicated_number", "country", "price_total", "_price_setup", "_price_monthly", "_currency"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PurchaseDedicatedNumberData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of currency
        if self.currency:
            _dict['_currency'] = self.currency.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PurchaseDedicatedNumberData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "dedicated_number": obj.get("dedicated_number"),
            "country": obj.get("country"),
            "price_total": obj.get("price_total"),
            "_price_setup": obj.get("_price_setup"),
            "_price_monthly": obj.get("_price_monthly"),
            "_currency": Currency.from_dict(obj["_currency"]) if obj.get("_currency") is not None else None
        })
        return _obj


