# coding: utf-8

"""
    SMS

    You can use the SMS endpoints to send and manage SMS, check the cost of sending SMS, view message history, and more. Integrate them into your system as part of your workflow.  Relevant guides: <a href=\"https://help.clicksend.com/article/h474eseq3a-how-many-characters-can-i-send-in-an-sms\" target=\"_blank\">How many characters can I send in an SMS?</a>, <a href=\"https://help.clicksend.com/article/1hd33n2xns-sms-status-delivery-receipt-expired\" target=\"_blank\">SMS status delivery receipt expired</a>, <a href=\"https://help.clicksend.com/en/articles/42195-unicode-vs-plain-text\" target=\"_blank\">Do you support non-English characters</a>, and <a href=\"https://help.clicksend.com/category/mfdctha7f0-country-specific-features-and-restrictions\" target=\"_blank\">Country Specific Features and Restrictions</a>. <div class=\"info-box\">   <h4><i class=\"fas fa-info-circle\"></i> Note :</h4>   ClickSend is pausing SMS messages containing URLs for new customers. Please remove links from messages to maintain uninterrupted delivery, or <a href=\"https://www.clicksend.com/gb/help/\" target=\"_blank\">contact support</a> to apply for approval for URL messaging. </div>

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class RegisterNumbersRequest(BaseModel):
    """
    RegisterNumbersRequest
    """ # noqa: E501
    full_name: StrictStr = Field(description="Legal full name of the individual registering the number. Must be a personal name, not a business name.", json_schema_extra={"examples": ["John Doe"]})
    company_name: StrictStr = Field(description="Legal business name of the organization requesting registration", json_schema_extra={"examples": ["ClickSend"]})
    email: StrictStr = Field(description="Contact email address for registration communications and notifications", json_schema_extra={"examples": ["john.doe@clicksend.com"]})
    website_url: StrictStr = Field(description="Official business website URL", json_schema_extra={"examples": ["https://clicksend.com"]})
    sample_message: StrictStr = Field(description="Representative example of messages that will be sent using this number", json_schema_extra={"examples": ["Get 20% off on your next purchase! Visit our website for details."]})
    primary_use_case: StrictStr = Field(description="Primary intended purpose for the registered number (e.g., Marketing, Notifications, Authentication)", json_schema_extra={"examples": ["Marketing"]})
    company_number: StrictStr = Field(description="Official support phone number of the organization requesting registration", json_schema_extra={"examples": ["+1-800-555-0199"]})
    area_code: StrictStr = Field(description="Your area codes, please provide your top 3 area codes in case your 1st choice is not available", json_schema_extra={"examples": ["416, 647, 905"]})
    __properties: ClassVar[List[str]] = ["full_name", "company_name", "email", "website_url", "sample_message", "primary_use_case", "company_number", "area_code"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RegisterNumbersRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RegisterNumbersRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "full_name": obj.get("full_name"),
            "company_name": obj.get("company_name"),
            "email": obj.get("email"),
            "website_url": obj.get("website_url"),
            "sample_message": obj.get("sample_message"),
            "primary_use_case": obj.get("primary_use_case"),
            "company_number": obj.get("company_number"),
            "area_code": obj.get("area_code")
        })
        return _obj


