# coding: utf-8

"""
    SMS

    You can use the SMS endpoints to send and manage SMS, check the cost of sending SMS, view message history, and more. Integrate them into your system as part of your workflow.  Relevant guides: <a href=\"https://help.clicksend.com/article/h474eseq3a-how-many-characters-can-i-send-in-an-sms\" target=\"_blank\">How many characters can I send in an SMS?</a>, <a href=\"https://help.clicksend.com/article/1hd33n2xns-sms-status-delivery-receipt-expired\" target=\"_blank\">SMS status delivery receipt expired</a>, <a href=\"https://help.clicksend.com/en/articles/42195-unicode-vs-plain-text\" target=\"_blank\">Do you support non-English characters</a>, and <a href=\"https://help.clicksend.com/category/mfdctha7f0-country-specific-features-and-restrictions\" target=\"_blank\">Country Specific Features and Restrictions</a>. <div class=\"info-box\">   <h4><i class=\"fas fa-info-circle\"></i> Note :</h4>   ClickSend is pausing SMS messages containing URLs for new customers. Please remove links from messages to maintain uninterrupted delivery, or <a href=\"https://www.clicksend.com/gb/help/\" target=\"_blank\">contact support</a> to apply for approval for URL messaging. </div>

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class Subaccount(BaseModel):
    """
    Subaccount
    """ # noqa: E501
    subaccount_id: Optional[StrictInt] = Field(default=None, description="The unique identifier for the subaccount.", json_schema_extra={"examples": [126]})
    api_username: Optional[StrictStr] = Field(default=None, description="The API username of the subaccount.", json_schema_extra={"examples": ["johndoe1"]})
    email: Optional[StrictStr] = Field(default=None, description="The email address of the subaccount.", json_schema_extra={"examples": ["johndoe1@awesome.com"]})
    phone_number: Optional[StrictStr] = Field(default=None, description="The phone number of the subaccount.", json_schema_extra={"examples": ["+15184811001"]})
    first_name: Optional[StrictStr] = Field(default=None, description="The first name of the subaccount.", json_schema_extra={"examples": ["John"]})
    last_name: Optional[StrictStr] = Field(default=None, description="The last name of the subaccount.", json_schema_extra={"examples": ["Doe"]})
    api_key: Optional[StrictStr] = Field(default=None, description="The API key of the subaccount.", json_schema_extra={"examples": ["F3702045-EB2C-0091-C211-7728048DCAE2"]})
    access_users: Optional[StrictInt] = Field(default=None, description="Flag indicating if the subaccount has access to users.", json_schema_extra={"examples": [1]})
    access_billing: Optional[StrictInt] = Field(default=None, description="Flag indicating if the subaccount has access to billing.", json_schema_extra={"examples": [1]})
    access_reporting: Optional[StrictInt] = Field(default=None, description="Flag indicating if the subaccount has access to reporting.", json_schema_extra={"examples": [1]})
    access_contacts: Optional[StrictInt] = Field(default=None, description="Flag indicating if the subaccount has access to contacts.", json_schema_extra={"examples": [1]})
    access_settings: Optional[StrictInt] = Field(default=None, description="Flag indicating if the subaccount has access to settings.", json_schema_extra={"examples": [1]})
    access_sms: Optional[StrictInt] = Field(default=None, description="Flag indicating if the subaccount has access to SMS.", json_schema_extra={"examples": [1]})
    access_email: Optional[StrictInt] = Field(default=None, description="Flag indicating if the subaccount has access to email.", json_schema_extra={"examples": [1]})
    access_voice: Optional[StrictInt] = Field(default=None, description="Flag indicating if the subaccount has access to voice services.", json_schema_extra={"examples": [1]})
    access_fax: Optional[StrictInt] = Field(default=None, description="Flag indicating if the subaccount has access to fax services.", json_schema_extra={"examples": [1]})
    access_post: Optional[StrictInt] = Field(default=None, description="Flag indicating if the subaccount has access to post services.", json_schema_extra={"examples": [1]})
    access_reseller: Optional[StrictInt] = Field(default=None, description="Flag indicating if the subaccount has access to reseller services.", json_schema_extra={"examples": [1]})
    access_mms: Optional[StrictInt] = Field(default=None, description="Flag indicating if the subaccount has access to MMS services.", json_schema_extra={"examples": [1]})
    share_campaigns: Optional[StrictInt] = Field(default=None, description="Flag indicating if the subaccount can share campaigns.", json_schema_extra={"examples": [0]})
    notes: Optional[StrictStr] = Field(default=None, description="Additional notes for the subaccount.")
    __properties: ClassVar[List[str]] = ["subaccount_id", "api_username", "email", "phone_number", "first_name", "last_name", "api_key", "access_users", "access_billing", "access_reporting", "access_contacts", "access_settings", "access_sms", "access_email", "access_voice", "access_fax", "access_post", "access_reseller", "access_mms", "share_campaigns", "notes"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Subaccount from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if notes (nullable) is None
        # and model_fields_set contains the field
        if self.notes is None and "notes" in self.model_fields_set:
            _dict['notes'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Subaccount from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "subaccount_id": obj.get("subaccount_id"),
            "api_username": obj.get("api_username"),
            "email": obj.get("email"),
            "phone_number": obj.get("phone_number"),
            "first_name": obj.get("first_name"),
            "last_name": obj.get("last_name"),
            "api_key": obj.get("api_key"),
            "access_users": obj.get("access_users"),
            "access_billing": obj.get("access_billing"),
            "access_reporting": obj.get("access_reporting"),
            "access_contacts": obj.get("access_contacts"),
            "access_settings": obj.get("access_settings"),
            "access_sms": obj.get("access_sms"),
            "access_email": obj.get("access_email"),
            "access_voice": obj.get("access_voice"),
            "access_fax": obj.get("access_fax"),
            "access_post": obj.get("access_post"),
            "access_reseller": obj.get("access_reseller"),
            "access_mms": obj.get("access_mms"),
            "share_campaigns": obj.get("share_campaigns"),
            "notes": obj.get("notes")
        })
        return _obj


