# coding: utf-8

"""
    SMS

    You can use the SMS endpoints to send and manage SMS, check the cost of sending SMS, view message history, and more. Integrate them into your system as part of your workflow.  Relevant guides: <a href=\"https://help.clicksend.com/article/h474eseq3a-how-many-characters-can-i-send-in-an-sms\" target=\"_blank\">How many characters can I send in an SMS?</a>, <a href=\"https://help.clicksend.com/article/1hd33n2xns-sms-status-delivery-receipt-expired\" target=\"_blank\">SMS status delivery receipt expired</a>, <a href=\"https://help.clicksend.com/en/articles/42195-unicode-vs-plain-text\" target=\"_blank\">Do you support non-English characters</a>, and <a href=\"https://help.clicksend.com/category/mfdctha7f0-country-specific-features-and-restrictions\" target=\"_blank\">Country Specific Features and Restrictions</a>. <div class=\"info-box\">   <h4><i class=\"fas fa-info-circle\"></i> Note :</h4>   ClickSend is pausing SMS messages containing URLs for new customers. Please remove links from messages to maintain uninterrupted delivery, or <a href=\"https://www.clicksend.com/gb/help/\" target=\"_blank\">contact support</a> to apply for approval for URL messaging. </div>

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from clicksend.models.attachment import Attachment
from clicksend.models.currency import Currency
from clicksend.models.send_email_request_to_inner import SendEmailRequestToInner
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class TransactionalEmail(BaseModel):
    """
    TransactionalEmail
    """ # noqa: E501
    user_id: Optional[StrictInt] = Field(default=None, description="The ID of the user.", json_schema_extra={"examples": [1]})
    subaccount_id: Optional[StrictInt] = Field(default=None, description="The ID of the subaccount.", json_schema_extra={"examples": [1]})
    from_email_address_id: Optional[StrictInt] = Field(default=None, description="The ID of the from email address.", json_schema_extra={"examples": [1]})
    from_name: Optional[StrictStr] = Field(default=None, description="The name of the sender.", json_schema_extra={"examples": ["Joanne Doe"]})
    to: Optional[List[SendEmailRequestToInner]] = Field(default=None, json_schema_extra={"examples": [[{"email": "test@clicksend.com", "name": "John Doe"}]]})
    cc: Optional[List[SendEmailRequestToInner]] = Field(default=None, json_schema_extra={"examples": [[{"email": "test2@clicksend.com", "name": "Jane Doe"}]]})
    bcc: Optional[List[SendEmailRequestToInner]] = Field(default=None, json_schema_extra={"examples": [[{"email": "test3@clicksend.com", "name": "Joseph Doe"}]]})
    subject: Optional[StrictStr] = Field(default=None, description="The subject of the email.", json_schema_extra={"examples": ["Test subject"]})
    body: Optional[StrictStr] = Field(default=None, description="The HTML body of the email.", json_schema_extra={"examples": ["Lorem ipsum"]})
    body_plain_text: Optional[StrictStr] = Field(default=None, description="The plain text body of the email.", json_schema_extra={"examples": ["Lorem ipsum"]})
    schedule: Optional[StrictInt] = Field(default=None, description="The timestamp indicating the scheduled time of the email.", json_schema_extra={"examples": [1507018182]})
    message_id: Optional[StrictStr] = Field(default=None, description="The ID of the email message.", json_schema_extra={"examples": ["21C632C1-3FCC-4EFF-8191-6079244F0142"]})
    status: Optional[StrictStr] = Field(default=None, description="The status of the email.", json_schema_extra={"examples": ["WaitApproval"]})
    status_text: Optional[StrictStr] = Field(default=None, description="The text description of the email status.", json_schema_extra={"examples": ["Accepted for delivery"]})
    soft_bounce_count: Optional[StrictInt] = Field(default=None, description="The count of soft bounces.", json_schema_extra={"examples": [0]})
    hard_bounce_count: Optional[StrictInt] = Field(default=None, description="The count of hard bounces.", json_schema_extra={"examples": [0]})
    price: Optional[StrictStr] = Field(default=None, description="The price of the email.", json_schema_extra={"examples": ["0.0050"]})
    date_added: Optional[StrictInt] = Field(default=None, description="The timestamp indicating when the email was added.", json_schema_extra={"examples": [1507018182]})
    custom_string: Optional[StrictStr] = Field(default=None, description="A custom string.")
    attachments: Optional[List[Attachment]] = Field(default=None, alias="_attachments", json_schema_extra={"examples": [[{"file_name": "text.txt", "content_type": "text/plain", "content_disposition": "attachment", "content_id": "text", "_attachment_file_url": "https://rest.clicksend.com/files/3C2284DC-7C37-47BA-8C95-3F12A4B987B7.txt"}]]})
    currency: Optional[Currency] = Field(default=None, alias="_currency")
    __properties: ClassVar[List[str]] = ["user_id", "subaccount_id", "from_email_address_id", "from_name", "to", "cc", "bcc", "subject", "body", "body_plain_text", "schedule", "message_id", "status", "status_text", "soft_bounce_count", "hard_bounce_count", "price", "date_added", "custom_string", "_attachments", "_currency"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TransactionalEmail from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in to (list)
        _items = []
        if self.to:
            for _item_to in self.to:
                if _item_to:
                    _items.append(_item_to.to_dict())
            _dict['to'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in cc (list)
        _items = []
        if self.cc:
            for _item_cc in self.cc:
                if _item_cc:
                    _items.append(_item_cc.to_dict())
            _dict['cc'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in bcc (list)
        _items = []
        if self.bcc:
            for _item_bcc in self.bcc:
                if _item_bcc:
                    _items.append(_item_bcc.to_dict())
            _dict['bcc'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in attachments (list)
        _items = []
        if self.attachments:
            for _item_attachments in self.attachments:
                if _item_attachments:
                    _items.append(_item_attachments.to_dict())
            _dict['_attachments'] = _items
        # override the default output from pydantic by calling `to_dict()` of currency
        if self.currency:
            _dict['_currency'] = self.currency.to_dict()
        # set to None if custom_string (nullable) is None
        # and model_fields_set contains the field
        if self.custom_string is None and "custom_string" in self.model_fields_set:
            _dict['custom_string'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TransactionalEmail from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "user_id": obj.get("user_id"),
            "subaccount_id": obj.get("subaccount_id"),
            "from_email_address_id": obj.get("from_email_address_id"),
            "from_name": obj.get("from_name"),
            "to": [SendEmailRequestToInner.from_dict(_item) for _item in obj["to"]] if obj.get("to") is not None else None,
            "cc": [SendEmailRequestToInner.from_dict(_item) for _item in obj["cc"]] if obj.get("cc") is not None else None,
            "bcc": [SendEmailRequestToInner.from_dict(_item) for _item in obj["bcc"]] if obj.get("bcc") is not None else None,
            "subject": obj.get("subject"),
            "body": obj.get("body"),
            "body_plain_text": obj.get("body_plain_text"),
            "schedule": obj.get("schedule"),
            "message_id": obj.get("message_id"),
            "status": obj.get("status"),
            "status_text": obj.get("status_text"),
            "soft_bounce_count": obj.get("soft_bounce_count"),
            "hard_bounce_count": obj.get("hard_bounce_count"),
            "price": obj.get("price"),
            "date_added": obj.get("date_added"),
            "custom_string": obj.get("custom_string"),
            "_attachments": [Attachment.from_dict(_item) for _item in obj["_attachments"]] if obj.get("_attachments") is not None else None,
            "_currency": Currency.from_dict(obj["_currency"]) if obj.get("_currency") is not None else None
        })
        return _obj


