# coding: utf-8

"""
    SMS

    You can use the SMS endpoints to send and manage SMS, check the cost of sending SMS, view message history, and more. Integrate them into your system as part of your workflow.  Relevant guides: <a href=\"https://help.clicksend.com/article/h474eseq3a-how-many-characters-can-i-send-in-an-sms\" target=\"_blank\">How many characters can I send in an SMS?</a>, <a href=\"https://help.clicksend.com/article/1hd33n2xns-sms-status-delivery-receipt-expired\" target=\"_blank\">SMS status delivery receipt expired</a>, <a href=\"https://help.clicksend.com/en/articles/42195-unicode-vs-plain-text\" target=\"_blank\">Do you support non-English characters</a>, and <a href=\"https://help.clicksend.com/category/mfdctha7f0-country-specific-features-and-restrictions\" target=\"_blank\">Country Specific Features and Restrictions</a>. <div class=\"info-box\">   <h4><i class=\"fas fa-info-circle\"></i> Note :</h4>   ClickSend is pausing SMS messages containing URLs for new customers. Please remove links from messages to maintain uninterrupted delivery, or <a href=\"https://www.clicksend.com/gb/help/\" target=\"_blank\">contact support</a> to apply for approval for URL messaging. </div>

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class VoiceReceipt(BaseModel):
    """
    VoiceReceipt
    """ # noqa: E501
    timestamp_send: Optional[StrictStr] = Field(default=None, description="Timestamp of the original send request in UNIX format. e.g 1439173980", json_schema_extra={"examples": ["1442381791"]})
    timestamp: Optional[StrictStr] = Field(default=None, description="Timestamp of delivery report in UNIX format. e.g 1439173981", json_schema_extra={"examples": ["1442381791"]})
    message_id: Optional[StrictStr] = Field(default=None, description="Message ID, returned when originally sending the message.", json_schema_extra={"examples": ["31BC271B-1E0C-45F6-9E7E-97186C46BB82"]})
    status_code: Optional[StrictStr] = Field(default=None, description="Status code. Refer to 'Voice Delivery Status Codes' in docs.", json_schema_extra={"examples": ["201"]})
    status_text: Optional[StrictStr] = Field(default=None, description="Status text.", json_schema_extra={"examples": ["Success: Message received on handset."]})
    error_code: Optional[StrictStr] = Field(default=None, description="Error code.")
    error_text: Optional[StrictStr] = Field(default=None, description="Error text.")
    custom_string: Optional[StrictStr] = Field(default=None, description="A custom string used when sending the original message.")
    message_type: Optional[StrictStr] = Field(default=None, description="voice (constant).", json_schema_extra={"examples": ["voice"]})
    digits: Optional[StrictStr] = Field(default=None, description="Numbers the recipient pressed on their keypad during the call. A blank string will be used if they didn't provide any input.")
    __properties: ClassVar[List[str]] = ["timestamp_send", "timestamp", "message_id", "status_code", "status_text", "error_code", "error_text", "custom_string", "message_type", "digits"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of VoiceReceipt from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if error_code (nullable) is None
        # and model_fields_set contains the field
        if self.error_code is None and "error_code" in self.model_fields_set:
            _dict['error_code'] = None

        # set to None if error_text (nullable) is None
        # and model_fields_set contains the field
        if self.error_text is None and "error_text" in self.model_fields_set:
            _dict['error_text'] = None

        # set to None if custom_string (nullable) is None
        # and model_fields_set contains the field
        if self.custom_string is None and "custom_string" in self.model_fields_set:
            _dict['custom_string'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of VoiceReceipt from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "timestamp_send": obj.get("timestamp_send"),
            "timestamp": obj.get("timestamp"),
            "message_id": obj.get("message_id"),
            "status_code": obj.get("status_code"),
            "status_text": obj.get("status_text"),
            "error_code": obj.get("error_code"),
            "error_text": obj.get("error_text"),
            "custom_string": obj.get("custom_string"),
            "message_type": obj.get("message_type"),
            "digits": obj.get("digits")
        })
        return _obj


