# coding: utf-8

"""
    SMS

    You can use the SMS endpoints to send and manage SMS, check the cost of sending SMS, view message history, and more. Integrate them into your system as part of your workflow.  Relevant guides: <a href=\"https://help.clicksend.com/article/h474eseq3a-how-many-characters-can-i-send-in-an-sms\" target=\"_blank\">How many characters can I send in an SMS?</a>, <a href=\"https://help.clicksend.com/article/1hd33n2xns-sms-status-delivery-receipt-expired\" target=\"_blank\">SMS status delivery receipt expired</a>, <a href=\"https://help.clicksend.com/en/articles/42195-unicode-vs-plain-text\" target=\"_blank\">Do you support non-English characters</a>, and <a href=\"https://help.clicksend.com/category/mfdctha7f0-country-specific-features-and-restrictions\" target=\"_blank\">Country Specific Features and Restrictions</a>. <div class=\"info-box\">   <h4><i class=\"fas fa-info-circle\"></i> Note :</h4>   ClickSend is pausing SMS messages containing URLs for new customers. Please remove links from messages to maintain uninterrupted delivery, or <a href=\"https://www.clicksend.com/gb/help/\" target=\"_blank\">contact support</a> to apply for approval for URL messaging. </div>

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from clicksend.models.voice_message_schedule import VoiceMessageSchedule
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class VoiceMessage(BaseModel):
    """
    VoiceMessage
    """ # noqa: E501
    var_date: Optional[StrictStr] = Field(default=None, description="The date, if applicable. May be null; see also `date_added`.", alias="date", json_schema_extra={"examples": ["1436871253"]})
    date_added: Optional[StrictInt] = Field(default=None, description="The Unix timestamp when the message was added.", json_schema_extra={"examples": [1436871253]})
    list_id: Optional[StrictStr] = Field(default=None, description="The ID of the list associated with the message, if applicable.")
    to: Optional[StrictStr] = Field(default=None, description="The recipient's phone number.", json_schema_extra={"examples": ["+61411111111"]})
    to_type: Optional[StrictStr] = Field(default=None, description="The type of recipient.", json_schema_extra={"examples": ["mobile"]})
    body: Optional[StrictStr] = Field(default=None, description="The body of the message.", json_schema_extra={"examples": ["Jelly liquorice marshmallow candy carrot cake 4Eyffjs1vL."]})
    var_from: Optional[StrictStr] = Field(default=None, description="The sender's phone number.", alias="from")
    lang: Optional[StrictStr] = Field(default=None, description="The language of the message.", json_schema_extra={"examples": ["en-au"]})
    voice: Optional[StrictStr] = Field(default=None, description="The voice of the message.", json_schema_extra={"examples": ["female"]})
    schedule: Optional[VoiceMessageSchedule] = None
    message_id: Optional[StrictStr] = Field(default=None, description="The ID of the message.", json_schema_extra={"examples": ["BF7AD270-0DE2-418B-B606-71D527D9C1AE"]})
    message_parts: Optional[VoiceMessageSchedule] = None
    message_price: Optional[StrictStr] = Field(default=None, description="The price of the message.", json_schema_extra={"examples": ["0.07"]})
    custom_string: Optional[StrictStr] = Field(default=None, description="The custom string of the message.", json_schema_extra={"examples": ["this is a test"]})
    user_id: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="The ID of the user.", json_schema_extra={"examples": [1]})
    subaccount_id: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="The ID of the subaccount.", json_schema_extra={"examples": [1]})
    country: Optional[StrictStr] = Field(default=None, description="The country code of the message.", json_schema_extra={"examples": ["AU"]})
    require_input: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="The require input of the message.", json_schema_extra={"examples": [0]})
    machine_detection: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="The machine detection of the message.", json_schema_extra={"examples": [0]})
    machine_detected: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Flag indicating if an answering machine was detected.", json_schema_extra={"examples": [0]})
    digits: Optional[StrictStr] = Field(default=None, description="The digits entered by the recipient, if any input was collected.")
    carrier: Optional[StrictStr] = Field(default=None, description="The carrier of the recipient's phone number.", json_schema_extra={"examples": ["Telstra"]})
    status_code: Optional[StrictStr] = Field(default=None, description="The status code of the message.", json_schema_extra={"examples": ["201"]})
    status_text: Optional[StrictStr] = Field(default=None, description="A human-readable description of the status.", json_schema_extra={"examples": ["Delivered"]})
    status: Optional[StrictStr] = Field(default=None, description="The status of the message.", json_schema_extra={"examples": ["SUCCESS"]})
    api_username: Optional[StrictStr] = Field(default=None, description="The API username associated with the message.", alias="_api_username", json_schema_extra={"examples": ["johndoe1"]})
    __properties: ClassVar[List[str]] = ["date", "date_added", "list_id", "to", "to_type", "body", "from", "lang", "voice", "schedule", "message_id", "message_parts", "message_price", "custom_string", "user_id", "subaccount_id", "country", "require_input", "machine_detection", "machine_detected", "digits", "carrier", "status_code", "status_text", "status", "_api_username"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of VoiceMessage from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of schedule
        if self.schedule:
            _dict['schedule'] = self.schedule.to_dict()
        # override the default output from pydantic by calling `to_dict()` of message_parts
        if self.message_parts:
            _dict['message_parts'] = self.message_parts.to_dict()
        # set to None if var_date (nullable) is None
        # and model_fields_set contains the field
        if self.var_date is None and "var_date" in self.model_fields_set:
            _dict['date'] = None

        # set to None if list_id (nullable) is None
        # and model_fields_set contains the field
        if self.list_id is None and "list_id" in self.model_fields_set:
            _dict['list_id'] = None

        # set to None if var_from (nullable) is None
        # and model_fields_set contains the field
        if self.var_from is None and "var_from" in self.model_fields_set:
            _dict['from'] = None

        # set to None if machine_detected (nullable) is None
        # and model_fields_set contains the field
        if self.machine_detected is None and "machine_detected" in self.model_fields_set:
            _dict['machine_detected'] = None

        # set to None if digits (nullable) is None
        # and model_fields_set contains the field
        if self.digits is None and "digits" in self.model_fields_set:
            _dict['digits'] = None

        # set to None if carrier (nullable) is None
        # and model_fields_set contains the field
        if self.carrier is None and "carrier" in self.model_fields_set:
            _dict['carrier'] = None

        # set to None if status_code (nullable) is None
        # and model_fields_set contains the field
        if self.status_code is None and "status_code" in self.model_fields_set:
            _dict['status_code'] = None

        # set to None if status_text (nullable) is None
        # and model_fields_set contains the field
        if self.status_text is None and "status_text" in self.model_fields_set:
            _dict['status_text'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of VoiceMessage from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "date": obj.get("date"),
            "date_added": obj.get("date_added"),
            "list_id": obj.get("list_id"),
            "to": obj.get("to"),
            "to_type": obj.get("to_type"),
            "body": obj.get("body"),
            "from": obj.get("from"),
            "lang": obj.get("lang"),
            "voice": obj.get("voice"),
            "schedule": VoiceMessageSchedule.from_dict(obj["schedule"]) if obj.get("schedule") is not None else None,
            "message_id": obj.get("message_id"),
            "message_parts": VoiceMessageSchedule.from_dict(obj["message_parts"]) if obj.get("message_parts") is not None else None,
            "message_price": obj.get("message_price"),
            "custom_string": obj.get("custom_string"),
            "user_id": obj.get("user_id"),
            "subaccount_id": obj.get("subaccount_id"),
            "country": obj.get("country"),
            "require_input": obj.get("require_input"),
            "machine_detection": obj.get("machine_detection"),
            "machine_detected": obj.get("machine_detected"),
            "digits": obj.get("digits"),
            "carrier": obj.get("carrier"),
            "status_code": obj.get("status_code"),
            "status_text": obj.get("status_text"),
            "status": obj.get("status"),
            "_api_username": obj.get("_api_username")
        })
        return _obj


